### ISSUE TITLE
GetLegendGraphic not working from TerriaJS for sci-wms endpoints

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#105]
TerriaJS is not showing the legend for layers from Sci-wms.   

It's isssuing requests like this:
http://sci-wms.whoi.edu/wms/datasets/usf_fvcom?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image/png&layer=salinity

which gives a 500 error.  

The logfile entry (which I grabbed via the web interface for sci-wms, using the latest goodies), reports this:

```
2015-11-06 13:21:37,415: ERROR/MainProcess] Internal Server Error: /wms/datasets/usf_fvcom
Traceback (most recent call last):
File "/home/usgs/miniconda/envs/sci-wms/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/usgs/miniconda/envs/sci-wms/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
return self.dispatch(request, *args, **kwargs)
File "/home/usgs/miniconda/envs/sci-wms/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
return handler(request, *args, **kwargs)
File "/home/usgs/python/sci-wms/wms/views.py", line 287, in get
response = getattr(dataset, reqtype.lower())(layer, request)
File "/home/usgs/python/sci-wms/wms/models/datasets/base.py", line 69, in getlegendgraphic
return glg_handler.filledcontour(request)
File "/home/usgs/python/sci-wms/wms/glg_handler.py", line 71, in filledcontour
fig, ax, norm = create_axis(request, get_position(request))
File "/home/usgs/python/sci-wms/wms/glg_handler.py", line 29, in create_axis
width = int(request.GET['width'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by kwilcox** [comment]
It's expecting width and height parameters. I'll have to check the wms spec to see if these are optional.

**Comment by rsignell-usgs** [comment]
@kwilcox, it turns out this is actually contained in the OGC "Styled Layer Descriptor" standards document (not the WMS standards document):
http://portal.opengeospatial.org/files/?artifact_id=1188
Page 62 specifies that both `WIDTH` and `HEIGHT` are optional.

**Comment by kwilcox** [comment]
Thanks for looking!  I'll update this to default to 110x264 (same as ncWMS... thanks for that info as well).

**Comment by rsignell-usgs** [comment]
I upgraded to 1.4, but these `GetLegendGraphic` requests from TerriaJS are resulting in proxy error:
http://sci-wms.whoi.edu/wms/datasets/usf_fvcom?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image/png&layer=salinity

http://sci-wms.whoi.edu/wms/datasets/smast_wq?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image/png&layer=DO

Any idea why?

**Comment by rsignell-usgs** [comment]
OMG.    @kwilcox figured out that this proxy error was actually caused by matplotlib 1.5.0, and downgrading to 1.4.3 fixed the problem.  :crying_cat_face:
