### ISSUE TITLE
ValueError: Length of color values array must be the same...

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#114]
When I run cell [5] in this notebook 
http://nbviewer.jupyter.org/gist/ocefpaf/190dd0792ea05c0e5d3d
which uses USF_FVCOM data,  I see errors in my `sci-wms.log` like:

```
[2016-02-11 11:22:12,131: ERROR/MainProcess] Length of color values array must be the same as either the number of triangulation points or triangles
Traceback (most recent call last):
  File "/home/usgs/python/sci-wms/wms/views.py", line 292, in get
    response = getattr(dataset, reqtype.lower())(layer, request)
  File "/home/usgs/python/sci-wms/wms/models/datasets/ugrid.py", line 274, in getmap
    return mpl_handler.tripcolor_response(tri_subset, data, request, data_location=data_location)
  File "/home/usgs/python/sci-wms/wms/mpl_handler.py", line 84, in tripcolor_response
    ax.tripcolor(tri_subset, facecolors=data, edgecolors='none', norm=norm, cmap=colormap)
  File "/home/usgs/miniconda/envs/sci-wms/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 7157, in tripcolor
    return mtri.tripcolor(self, *args, **kwargs)
  File "/home/usgs/miniconda/envs/sci-wms/lib/python3.5/site-packages/matplotlib/tri/tripcolor.py", line 89, in tripcolor
    raise ValueError('Length of color values array must be the same '
ValueError: Length of color values array must be the same as either the number of triangulation points or triangles
```

What causes this type of error? 
Should I be concerned?

**Comment by kwilcox** [comment]
Does it work as expected other than this error?

**Comment by kwilcox** [comment]
Not getting this anymore with `matplotlib>2.0`
