### ISSUE TITLE
What is procedure for migrations in a docker container so that the image can be re-run after a host shutdown (and isn't a custom topology volume always necessary with docker)?

### ISSUE THREAD

**Issue by cbcunc** [sci-wms/sci-wms#121]
Running docker container with -it to capture run.sh output. Start up normal. Login normal. Update demo datasets normal. Select ugrid dataset on leaflet demo, normal:
```
pylantic:~ cbc$ rm sciwms/db/sci-wms.db
pylantic:~ cbc$ docker run --rm -it -p 7002:7002 -v /Users/cbc/sciwms/db:/srv/sci-wms/sciwms/db/ axiom/sci-wms
Sourcing profile...
Migrating sci-wms...
Operations to perform:
  Synchronize unmigrated apps: grappelli, rest_framework, messages, staticfiles, admindocs, wmsrest
  Apply all migrations: sessions, auth, admin, contenttypes, sites, wms
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying wms.0001_initial... OK
  Applying wms.0002_auto_20150302_1106... OK
  Applying wms.0003_auto_20150302_1510... OK
  Applying wms.0004_auto_20150310_0955... OK
  Applying wms.0005_layer... OK
  Applying wms.0006_auto_20150424_1058... OK
  Applying wms.0007_auto_20150424_1604... OK
  Applying wms.0008_auto_20150428_2136... OK
  Applying wms.0009_auto_20150428_2030... OK
  Applying wms.0010_auto_20150428_2201... OK
  Applying wms.0011_auto_20150428_2211... OK
  Applying wms.0012_layer_default_max... OK
  Applying wms.0013_layer_default_min... OK
  Applying wms.0014_auto_20150428_2247... OK
  Applying wms.0015_change_testing_datasets... OK
  Applying wms.0016_layer_std_name... OK
  Applying wms.0017_create_layers... OK
  Applying wms.0018_add_style_to_virtuallayers... OK
  Applying wms.0019_remove_virtuallayer... OK
  Applying wms.0020_add_back_virtuallayer... OK
  Applying wms.0021_auto_20150429_1429... OK
  Applying wms.0022_auto_20150429_1533... OK
  Applying wms.0023_auto_20150501_1427... OK
  Applying wms.0024_auto_20150501_1731... OK
  Applying wms.0025_auto_20150504_1143... OK
  Applying wms.0026_dataset_slug... OK
  Applying wms.0027_auto_20150602_1603... OK
  Applying wms.0028_auto_20150710_1637... OK
  Applying wms.0029_auto_20150716_1639... OK
  Applying wms.0030_auto_20150716_1648... OK
  Applying wms.0031_auto_20151029_1205... OK
  Applying wms.0032_auto_20151030_1031... OK
  Applying wms.0033_auto_20151030_1103... OK
  Applying wms.0034_auto_20151030_1140... OK
Collecting sci-wms static assets...
========================================================================
sci-wms user:         "sciwmsuser"
sci-wms password:     "IKJY04qNBdll83Ez"
========================================================================
Starting sci-wms...
```

Select std_salt as variable to display on leaflet demo. Area in region of mouth of Columbia River is painted. Results in usual warnings about no triangles, axes not compatible with layout, and future warning on element-wise comparison: 

```
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/figure.py:1653: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "

WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/figure.py:1653: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "

WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/figure.py:1653: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "

WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/figure.py:1653: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "

WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/figure.py:1653: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "

WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/figure.py:1653: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "

WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):

WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:wms:No triangles in field of view, returning empty tile.
WARNING:py.warnings:/opt/conda/lib/python3.4/site-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):

```

Exit container with control-C. Container not retained as result of -rm on docker run options as per docs. Re-run image in a fresh container, keeping the updated database. Red letter notice appears that models have changed without migrating:

```
pylantic:~ cbc$ docker run --rm -it -p 7002:7002 -v /Users/cbc/sciwms/db:/srv/sci-wms/sciwms/db/ axiom/sci-wms
Sourcing profile...
Migrating sci-wms...
Operations to perform:
  Synchronize unmigrated apps: wmsrest, staticfiles, admindocs, messages, rest_framework, grappelli
  Apply all migrations: auth, sessions, admin, sites, contenttypes, wms
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Collecting sci-wms static assets...
========================================================================
sci-wms user:         "sciwmsuser"
sci-wms password:     "Jb9iOqQ7cRM4mJrP"
========================================================================
Starting sci-wms...
```

Re-run image in fresh container with an entrrypoint override in order to run manage.py before restarting server:

```
pylantic:Docker cbc$ docker run --rm -it -p 7002:7002 --name sciwms --entrypoint="" -v /Users/cbc/sciwms/db:/srv/sci-wms/sciwms/db/ axiom/sci-wms /bin/bash
root@d5b9118a776f:/srv/sci-wms# export DJANGO_SETTINGS_MODULE="sciwms.settings.prod"
root@d5b9118a776f:/srv/sci-wms# python manage.py makemigrations
Migrations for 'wms':
  0035_auto_20170207_1214.py:
    - Create proxy model UGridTideDataset
    - Alter field type on dataset
root@d5b9118a776f:/srv/sci-wms# python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: grappelli, staticfiles, admindocs, wmsrest, rest_framework, messages
  Apply all migrations: wms, sessions, admin, contenttypes, auth, sites
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying wms.0035_auto_20170207_1214... OK
root@d5b9118a776f:/srv/sci-wms# docker/run.sh
Sourcing profile...
Migrating sci-wms...
Operations to perform:
  Synchronize unmigrated apps: admindocs, staticfiles, messages, wmsrest, rest_framework, grappelli
  Apply all migrations: sites, sessions, contenttypes, admin, wms, auth
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
Collecting sci-wms static assets...
========================================================================
sci-wms user:         "sciwmsuser"
sci-wms password:     "Aa7B0jOSpWk6gdQZ"
========================================================================
Starting sci-wms...
```

Go back to leaflet demo and selected std_salt on UGridTest dataset. Map is not update and a slew of exceptions occur:

```
ERROR:django.request:Internal Server Error: /wms/datasets/ugridtest
Traceback (most recent call last):
  File "/opt/conda/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/sci-wms/wms/views.py", line 292, in get
    response = getattr(dataset, reqtype.lower())(layer, request)
  File "/srv/sci-wms/wms/models/datasets/ugrid.py", line 216, in getmap
    ug = UGrid.from_ncfile(self.topology_file, mesh_name=mesh_name)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/ugrid.py", line 130, in from_ncfile
    read_netcdf.load_grid_from_ncfilename(nc_url, grid, mesh_name, load_data)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/read_netcdf.py", line 259, in load_grid_from_ncfilename
    with netCDF4.Dataset(filename, 'r') as nc:
  File "netCDF4/_netCDF4.pyx", line 1747, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11907)
RuntimeError: No such file or directory
ERROR:tornado.access:500 GET /wms/datasets/ugridtest?service=WMS&request=GetMap&version=1.1.1&layers=std_salt&styles=filledcontours_cubehelix&format=image/png&transparent=true&height=256&width=256&colorscalerange=0,10&numcontours=20&logscale=false&srs=EPSG:3857&bbox=-12523442.714243276,5009377.085697309,-10018754.171394622,7514065.628545966 (172.17.0.1) 117.76ms
ERROR:django.request:Internal Server Error: /wms/datasets/ugridtest
Traceback (most recent call last):
  File "/opt/conda/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/sci-wms/wms/views.py", line 292, in get
    response = getattr(dataset, reqtype.lower())(layer, request)
  File "/srv/sci-wms/wms/models/datasets/ugrid.py", line 216, in getmap
    ug = UGrid.from_ncfile(self.topology_file, mesh_name=mesh_name)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/ugrid.py", line 130, in from_ncfile
    read_netcdf.load_grid_from_ncfilename(nc_url, grid, mesh_name, load_data)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/read_netcdf.py", line 259, in load_grid_from_ncfilename
    with netCDF4.Dataset(filename, 'r') as nc:
  File "netCDF4/_netCDF4.pyx", line 1747, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11907)
RuntimeError: No such file or directory
ERROR:tornado.access:500 GET /wms/datasets/ugridtest?service=WMS&request=GetMap&version=1.1.1&layers=std_salt&styles=filledcontours_cubehelix&format=image/png&transparent=true&height=256&width=256&colorscalerange=0,10&numcontours=20&logscale=false&srs=EPSG:3857&bbox=-15028131.257091932,2504688.5428486546,-12523442.714243276,5009377.085697309 (172.17.0.1) 89.83ms
ERROR:django.request:Internal Server Error: /wms/datasets/ugridtest
Traceback (most recent call last):
  File "/opt/conda/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/sci-wms/wms/views.py", line 292, in get
    response = getattr(dataset, reqtype.lower())(layer, request)
  File "/srv/sci-wms/wms/models/datasets/ugrid.py", line 216, in getmap
    ug = UGrid.from_ncfile(self.topology_file, mesh_name=mesh_name)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/ugrid.py", line 130, in from_ncfile
    read_netcdf.load_grid_from_ncfilename(nc_url, grid, mesh_name, load_data)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/read_netcdf.py", line 259, in load_grid_from_ncfilename
    with netCDF4.Dataset(filename, 'r') as nc:
  File "netCDF4/_netCDF4.pyx", line 1747, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11907)
RuntimeError: No such file or directory
ERROR:django.request:Internal Server Error: /wms/datasets/ugridtest
Traceback (most recent call last):
  File "/opt/conda/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/sci-wms/wms/views.py", line 292, in get
    response = getattr(dataset, reqtype.lower())(layer, request)
  File "/srv/sci-wms/wms/models/datasets/ugrid.py", line 216, in getmap
    ug = UGrid.from_ncfile(self.topology_file, mesh_name=mesh_name)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/ugrid.py", line 130, in from_ncfile
    read_netcdf.load_grid_from_ncfilename(nc_url, grid, mesh_name, load_data)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/read_netcdf.py", line 259, in load_grid_from_ncfilename
    with netCDF4.Dataset(filename, 'r') as nc:
  File "netCDF4/_netCDF4.pyx", line 1747, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11907)
RuntimeError: No such file or directory
ERROR:django.request:Internal Server Error: /wms/datasets/ugridtest
Traceback (most recent call last):
  File "/opt/conda/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/sci-wms/wms/views.py", line 292, in get
    response = getattr(dataset, reqtype.lower())(layer, request)
  File "/srv/sci-wms/wms/models/datasets/ugrid.py", line 216, in getmap
    ug = UGrid.from_ncfile(self.topology_file, mesh_name=mesh_name)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/ugrid.py", line 130, in from_ncfile
    read_netcdf.load_grid_from_ncfilename(nc_url, grid, mesh_name, load_data)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/read_netcdf.py", line 259, in load_grid_from_ncfilename
    with netCDF4.Dataset(filename, 'r') as nc:
  File "netCDF4/_netCDF4.pyx", line 1747, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11907)
RuntimeError: No such file or directory
ERROR:django.request:Internal Server Error: /wms/datasets/ugridtest
Traceback (most recent call last):
  File "/opt/conda/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/sci-wms/wms/views.py", line 292, in get
    response = getattr(dataset, reqtype.lower())(layer, request)
  File "/srv/sci-wms/wms/models/datasets/ugrid.py", line 216, in getmap
    ug = UGrid.from_ncfile(self.topology_file, mesh_name=mesh_name)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/ugrid.py", line 130, in from_ncfile
    read_netcdf.load_grid_from_ncfilename(nc_url, grid, mesh_name, load_data)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/read_netcdf.py", line 259, in load_grid_from_ncfilename
    with netCDF4.Dataset(filename, 'r') as nc:
  File "netCDF4/_netCDF4.pyx", line 1747, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11907)
RuntimeError: No such file or directory
ERROR:django.request:Internal Server Error: /wms/datasets/ugridtest
Traceback (most recent call last):
  File "/opt/conda/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/sci-wms/wms/views.py", line 292, in get
    response = getattr(dataset, reqtype.lower())(layer, request)
  File "/srv/sci-wms/wms/models/datasets/ugrid.py", line 216, in getmap
    ug = UGrid.from_ncfile(self.topology_file, mesh_name=mesh_name)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/ugrid.py", line 130, in from_ncfile
    read_netcdf.load_grid_from_ncfilename(nc_url, grid, mesh_name, load_data)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/read_netcdf.py", line 259, in load_grid_from_ncfilename
    with netCDF4.Dataset(filename, 'r') as nc:
  File "netCDF4/_netCDF4.pyx", line 1747, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11907)
RuntimeError: No such file or directory
ERROR:tornado.access:500 GET /wms/datasets/ugridtest?service=WMS&request=GetMap&version=1.1.1&layers=std_salt&styles=filledcontours_cubehelix&format=image/png&transparent=true&height=256&width=256&colorscalerange=0,10&numcontours=20&logscale=false&srs=EPSG:3857&bbox=-10018754.171394622,2504688.5428486546,-7514065.628545966,5009377.085697309 (172.17.0.1) 303.36ms
ERROR:django.request:Internal Server Error: /wms/datasets/ugridtest
Traceback (most recent call last):
  File "/opt/conda/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/sci-wms/wms/views.py", line 292, in get
    response = getattr(dataset, reqtype.lower())(layer, request)
  File "/srv/sci-wms/wms/models/datasets/ugrid.py", line 216, in getmap
    ug = UGrid.from_ncfile(self.topology_file, mesh_name=mesh_name)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/ugrid.py", line 130, in from_ncfile
    read_netcdf.load_grid_from_ncfilename(nc_url, grid, mesh_name, load_data)
  File "/opt/conda/lib/python3.4/site-packages/pyugrid/read_netcdf.py", line 259, in load_grid_from_ncfilename
    with netCDF4.Dataset(filename, 'r') as nc:
  File "netCDF4/_netCDF4.pyx", line 1747, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11907)
RuntimeError: No such file or directory
ERROR:tornado.access:500 GET /wms/datasets/ugridtest?service=WMS&request=GetMap&version=1.1.1&layers=std_salt&styles=filledcontours_cubehelix&format=image/png&transparent=true&height=256&width=256&colorscalerange=0,10&numcontours=20&logscale=false&srs=EPSG:3857&bbox=-10018754.171394622,5009377.085697309,-7514065.628545966,7514065.628545966 (172.17.0.1) 334.42ms
ERROR:tornado.access:500 GET /wms/datasets/ugridtest?service=WMS&request=GetMap&version=1.1.1&layers=std_salt&styles=filledcontours_cubehelix&format=image/png&transparent=true&height=256&width=256&colorscalerange=0,10&numcontours=20&logscale=false&srs=EPSG:3857&bbox=-12523442.714243276,2504688.5428486546,-10018754.171394622,5009377.085697309 (172.17.0.1) 329.40ms
ERROR:tornado.access:500 GET /wms/datasets/ugridtest?service=WMS&request=GetMap&version=1.1.1&layers=std_salt&styles=filledcontours_cubehelix&format=image/png&transparent=true&height=256&width=256&colorscalerange=0,10&numcontours=20&logscale=false&srs=EPSG:3857&bbox=-15028131.257091932,5009377.085697309,-12523442.714243276,7514065.628545966 (172.17.0.1) 330.01ms
ERROR:tornado.access:500 GET /wms/datasets/ugridtest?service=WMS&request=GetMap&version=1.1.1&layers=std_salt&styles=filledcontours_cubehelix&format=image/png&transparent=true&height=256&width=256&colorscalerange=0,10&numcontours=20&logscale=false&srs=EPSG:3857&bbox=-7514065.628545966,5009377.085697309,-5009377.085697311,7514065.628545966 (172.17.0.1) 331.01ms
ERROR:tornado.access:500 GET /wms/datasets/ugridtest?service=WMS&request=GetMap&version=1.1.1&layers=std_salt&styles=filledcontours_cubehelix&format=image/png&transparent=true&height=256&width=256&colorscalerange=0,10&numcontours=20&logscale=false&srs=EPSG:3857&bbox=-7514065.628545966,2504688.5428486546,-5009377.085697311,5009377.085697309 (172.17.0.1) 157.90ms
```

Same thing happens if using docker -it exec /bin/bash to manage migrations and the image is restarted.

What is the intention here? Containers in production will go down on occasion and have to be brought back up without rebuilding all datasets from scratch. While the container is running, datasets will need to be added, updated, and db migrated. So would the image need rerunning on each dataset?

Update: if I use a custom topology local volumne, then I don't get the netCDF4 traceback and the map displays. Isn't it necessary in the deployments docs to insist on using a topology volume when running the container instead of documenting it as optional?

However, the migration message still appear on startup, even with a topolgy volume. Is the intention to run migrations on every restart of the image?

**Comment by kwilcox** [comment]
#### migrations
I agree that if you are using the same DB volume between restarts that there should be no migrations run after the initial `run`. I'll have to take a look at this. It should only apply each migration once (when you use a new database or when `sci-wms` updates with a database migration).

#### topology dir
In production you should always be using the same topology volume between restarts... if you don't you would have to "update" each datasets everytime you re-run the docker container. This could be clearer in the docs... but not to the point of being required outside of production runs.

**Comment by rsignell-usgs** [comment]
Not sure what is going wrong here.  

My sci-wms Docker container is working fine.   :relaxed: 

I am starting it with `docker-compose up -d sci-wms` with this `docker-compose.yml`:
```
###
# sci-wms:  python-based wms for ugrid, sgrid
###

sci-wms:
  image: axiom/sci-wms
  ports:
    - "7002:7002"
  environment: 
    - SCIWMS_USERNAME=admin
    - SCIWMS_PASSWORD=XXXXXX
  container_name: sci-wms
  volumes:
    - /opt/docker/sci-wms/topology:/srv/sci-wms/wms/topology 
    - /opt/docker/sci-wms/db:/srv/sci-wms/sciwms/db
```

Here's an example of some sci-wms WMS layers from ASGS being displayed in TerriaJS: http://gamone.whoi.edu/terriajs/#https://rawgit.com/USGS-CMG/terriajs-dive/master/examples/sci-wms.json

![2017-02-16_10-19-40](https://cloud.githubusercontent.com/assets/1872600/23027194/93dab56e-f431-11e6-8077-fa920b3b5b4d.jpg)

**Comment by kwilcox** [comment]
Chris is trying to build the docker images that no doubt will have some issues since the IOOS -> conda-forge transition. I can take a look when I get a free moment

**Comment by rsignell-usgs** [comment]
Yes, but I think Chris is only trying to build the container because he couldn't figure out how to get your container working.   

 Is that right @cbcunc? 

So just trying to help get the existing container working for him.

**Comment by cbcunc** [comment]
Partially correct. @rsignell-usgs. I can get it working. It just throws makemigration errors when restarted after updating datasets. You can't see if if you run detached. Look at stdout because not everything going on is showing up in logs:

$ docker-compose up sci-wms
\# Update some datasets
$ docker stop sci-wms
\# run docker stop is another terminal on the docker host
$ docker start -a sci-wms

In stdout of docker start -a:

```
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate'
  to apply them.
```

Thanks for access to your docker-compose.yml. I was thinking of asking if this image should be run in a swarm in order to ssh into the sci-wms machine and run makemigrations that way.

**Comment by rsignell-usgs** [comment]
@cbcunc , okay, I see what you mean:
![2017-02-16_12-02-38](https://cloud.githubusercontent.com/assets/1872600/23031732/ff654606-f43f-11e6-9b3e-0fa86dbe8547.png)

**Comment by drf5n** [comment]
So how does one follow the  `manage.py ... ` advice in:

```
$ docker run  -it  -p 7002:7002 -v /home/drf/sciwms/db:/srv/sci-wms/sciwms/db/ -v /home/drf/sciwms/topology:/srv/sci-wms/sciwms/topology/  axiom/sci-wms 
Sourcing profile...
Migrating sci-wms...
Operations to perform:
  Synchronize unmigrated apps: messages, admindocs, grappelli, rest_framework, wmsrest, staticfiles
  Apply all migrations: contenttypes, sessions, sites, wms, auth, admin
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Collecting sci-wms static assets...
```

**Comment by kwilcox** [comment]
You can safely ignore that migration message. It is due to `matplotlib` changing the available palettes since I last ran the migration generation.

I've had a `background_jobs` branch of `sci-wms` going for some time and just attempted to merge it in and make a new release but I'll have to fix a bunch of test errors and library incompatibilities first. Not today... but soon...

**Comment by drf5n** [comment]
Thanks.

I really don't know docker much at all and I found that I could get into a shell to run the commands with:

```
$ docker ps 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                    NAMES
8896086518bd        axiom/sci-wms       "docker/run.sh"     11 minutes ago      Up 11 minutes       0.0.0.0:7002->7002/tcp   sad_rosalind
$ docker exec -it 8896086518bd bash
root@8896086518bd:/srv/sci-wms# ./manage.py makemigrations ; ./manage.py migrate
exit

```
From the shell, I can also see errors like @cbcunc reported in the logs/sci-wms.log file.

Am I not using a good topology dir if i invoke it like:

```
docker run  -d  -p 7002:7002 -v /home/drf/sciwms/db:/srv/sci-wms/sciwms/db/ -v /home/drf/sciwms/topology:/srv/sci-wms/sciwms/topology/  axiom/sci-wms

```

**Comment by kwilcox** [comment]
@drf5n @cbcunc There is a new version available that fixes some bugs and updates the documentation. You might have better luck now!

http://sci-wms.github.io/sci-wms/deployment.html
