### ISSUE TITLE
"local variable 'coordinates' referenced before assignment" on ADCIRC ec2015 dataset

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#124]
I tried using sci-wms for the first time in a while yesterday because I have a 2 million node UGRID dataset that is overwhelming ncWMS2 (the ADCIRC ec2015 tidal database).   

https://gamone.whoi.edu/thredds/catalog/usgs/vault0/models/tides/ec2015/catalog.html?dataset=usgs/vault0/models/tides/ec2015/f53.ncml

on my sci-wms here: https://gamone.whoi.edu/wms/demo

with getcaps here:
https://gamone.whoi.edu/wms/datasets/ec2015?REQUEST=GetCapabilities

The client is getting 500 errors from getmap requests like:
https://gamone.whoi.edu/wms/datasets/ec2015?service=WMS&request=GetMap&version=1.1.1&layers=depth&styles=filledcontours_jet&format=image/png&transparent=true&height=256&width=256&colorscalerange=0.0,500.0&numcontours=60&logscale=false&srs=EPSG:3857&bbox=-7514065.628545966,2504688.5428486555,-5009377.085697311,5009377.08569731

and in the sci-wms logs I see this error `local variable 'coordinates' referenced before assignment`:

```python-traceback
[2018-03-23 06:14:01,292: ERROR/MainProcess] Internal Server Error: /wms/datasets/ec2015
Traceback (most recent call last):
  File "/opt/conda/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/sci-wms/wms/views.py", line 292, in get
    response = getattr(dataset, reqtype.lower())(layer, request)
  File "/srv/sci-wms/wms/models/datasets/ugrid.py", line 208, in getmap
    time_index, time_value = self.nearest_time(layer, request.GET['time'])
  File "/srv/sci-wms/wms/models/datasets/netcdf.py", line 243, in nearest_time
    time_var_name = find_appropriate_time(var_obj, time_vars)
  File "/srv/sci-wms/wms/utils.py", line 104, in find_appropriate_time
    c_intersects = list(coordinates.intersection(time_set))
UnboundLocalError: local variable 'coordinates' referenced before assignment
```
Anyone have ideas what this means, and why this particular dataset would expose this issue?

**Comment by kwilcox** [comment]
Your variables need the `coordinates` attribute!

**Comment by rsignell-usgs** [comment]
Yup, that fixed it!
