### ISSUE TITLE
Adding a dataset

### ISSUE THREAD

**Issue by ghost** [sci-wms/sci-wms#140]
After following the instructions using docker, I found that I can't add a new dataset, it gives me a server error. The buttons to add layers don't work either.
The logs output is says something related to the type, but I'm adding the type of the dataset:

File "/opt/conda/lib/python3.6/site-packages/typedmodels/models.py", line 369, in save
raise RuntimeError("Untyped %s cannot be saved." % self.__class__.__name__)
RuntimeError: Untyped Dataset cannot be saved.
[2018-10-25 11:17:10,573: ERROR/MainProcess] Internal Server Error: /admin/wms/dataset/add/

Any ideas would be appreciated.
Many thanks,
Paola

**Comment by kwilcox** [comment]
Can you post a link to the file you are trying to add as a dataset?

**Comment by ghost** [comment]
Thanks for your answer. This is the dataset I want to add:
http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_GOM3_FORECAST.nc.html

However, I think my installation is not working as it should (I didn't pass most of the tests). When I request the admin url I get this error:

BlockingIOError: [Errno 11] Resource temporarily unavailable
[2018-10-26 10:38:35 +0000] [95] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 66, in handle
    six.reraise(*sys.exc_info())
  File "/opt/conda/lib/python3.6/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/opt/conda/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 129, in handle_request
    six.reraise(*sys.exc_info())
  File "/opt/conda/lib/python3.6/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 112, in handle_request
    resp.write_file(respiter)
  File "/opt/conda/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 403, in write_file
    if not self.sendfile(respiter):
  File "/opt/conda/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 393, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
BlockingIOError: [Errno 11] Resource temporarily unavailable

I followed this url to install it:

https://sci-wms.github.io/sci-wms/docs/installation.html#docker

Many thanks.

**Comment by kwilcox** [comment]
The install instructions you posted above are for an old version. I'll have to clean those up. Use this link for installation:  https://sci-wms.github.io/sci-wms/deployment.html

**Comment by mapsa** [comment]
I followed the installation instructions using docker and the latest release 1.6.0 ( https://github.com/sci-wms/sci-wms/releases).  I also installed the version 2.0.0 with the same result.

Here I left a copy of the dataset I'm working:

https://1drv.ms/u/s!AlDn2ehuc7ncqnr3t6xDVTm-CyeJ

Thanks,
Paola

**Comment by kwilcox** [comment]
@mapsa Thank you for the dataset link. Your file is not compliant with the [CF-UGRID specification](http://ugrid-conventions.github.io/ugrid-conventions/). For an example FVCOM dataset that is compliant set [this](http://www.smast.umassd.edu:8080/thredds/dodsC/FVCOM/NECOFS/Forecasts/NECOFS_GOM3_FORECAST.nc.html).

**Comment by mapsa** [comment]
OK, thanks for your help, I'll fix the dataset!

**Comment by kwilcox** [comment]
@paraborrar You need to resolve your installation issues before trying to add a dataset. The OPeNDAP URL you listed above works fine for me.

![selection_430](https://user-images.githubusercontent.com/13939/48013559-91f10780-e0f2-11e8-8341-4a0da40ee308.png)

![selection_431](https://user-images.githubusercontent.com/13939/48013551-8ef61700-e0f2-11e8-90db-21e4512e9dc7.png)

**Comment by mapsa** [comment]
I've fixed the installation and I can see the same layer now. I'll fix my dataset.
Many thanks.
