### ISSUE TITLE
Problem upgrading sci-wms 

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#99]
To upgrade to a new version of sci-wms, I've been doing this:

```
sudo supervisorctl  stop sciwms 
cd /home/usgs/python/sci-wms
git pull
source activate sci-wms
DJANGO_SETTINGS_MODULE="sciwms.settings.prod" python manage.py migrate  
sudo supervisorctl start sciwms
```

Usually this reports a bunch of warnings:

```
Cannot create cookie file
```

but then works okay.   

Today it's giving me those warnings, but then failing with "conficting migrations detected"

```
(sci-wms)usgs@gam:~/python/sci-wms$ DJANGO_SETTINGS_MODULE="sciwms.settings.prod" python manage.py migrate
Cannot create cookie file
Cannot create cookie file
Cannot create cookie file
Cannot create cookie file
Cannot create cookie file
Cannot create cookie file
Cannot create cookie file
CommandError: Conflicting migrations detected (0031_auto_20150826_1557, 0034_auto_20151030_1140 in wms).
To fix them run 'python manage.py makemigrations --merge'
```

If I then try the suggested command:

```
(sci-wms)usgs@gam:~/python/sci-wms$ DJANGO_SETTINGS_MODULE="sciwms.settings.prod" python manage.py makemigrations --merge
```

I get back:

```
(sci-wms)usgs@gam:~/python/sci-wms$ DJANGO_SETTINGS_MODULE="sciwms.settings.prod" python manage.py makemigrations --merge
Cannot create cookie file
Cannot create cookie file
Cannot create cookie file
Cannot create cookie file
Cannot create cookie file
Cannot create cookie file
Cannot create cookie file
Merging wms
  Branch 0031_auto_20150826_1557
    - Alter field slug on dataset
  Branch 0034_auto_20151030_1140
    - Delete model DatasetOriginal
    - Alter field abstract on dataset
    - Alter field display_all_timesteps on dataset
    - Alter field json on dataset
    - Alter field keep_up_to_date on dataset
    - Alter field name on dataset
    - Alter field slug on dataset
    - Alter field title on dataset
    - Alter field abstract on group
    - Alter field datasets on group
    - Alter field default_max on layer
    - Alter field default_min on layer
    - Alter field description on layer
    - Alter field logscale on layer
    - Alter field std_name on layer
    - Alter field units on layer
    - Alter field var_name on layer
    - Alter field abstract on server
    - Alter field contact_city_address on server
    - Alter field contact_code_address on server
    - Alter field contact_country_address on server
    - Alter field contact_email on server
    - Alter field contact_organization on server
    - Alter field contact_person on server
    - Alter field contact_position on server
    - Alter field contact_state_address on server
    - Alter field contact_street_address on server
    - Alter field contact_telephone on server
    - Alter field keywords on server
    - Alter field title on server
    - Alter field colormap on style
    - Alter field description on style
    - Alter field image_type on style
    - Alter field default_max on variable
    - Alter field default_min on variable
    - Alter field logscale on variable
    - Alter field std_name on variable
    - Alter field units on variable
    - Alter field default_max on virtuallayer
    - Alter field default_min on virtuallayer
    - Alter field description on virtuallayer
    - Alter field logscale on virtuallayer
    - Alter field std_name on virtuallayer
    - Alter field units on virtuallayer
    - Alter field var_name on virtuallayer
    - Add field default_style to layer
    - Add field default_style to virtuallayer
    - Add field default_numcontours to layer
    - Add field default_numcontours to virtuallayer
    - Alter field default_style on layer
    - Alter field image_type on style
    - Alter field default_style on virtuallayer
    - Raw Python operation

Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Do you want to merge these migration branches? [y/N] 
```

Answering "y" produced the response:

```
Created new merge migration /home/usgs/python/sci-wms/wms/migrations/0035_merge.py
```

I then did:

```
 sudo supervisorctl start sciwms
```

and all seemed okay.   

But when I tried to access http://sci-wms.whoi.edu/wms, I got a `Proxy Error` response, and looking in the sci-wms log at `/home/usgs/python/sci-wms/sci-wms/log`, I see this error:

```
[2015-11-02 07:16:52,298: ERROR/MainProcess] Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/usgs/miniconda/envs/sci-wms/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/home/usgs/miniconda/envs/sci-wms/lib/python2.7/site-packages/django/middleware/common.py", line 72, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/usgs/miniconda/envs/sci-wms/lib/python2.7/site-packages/django/core/urlresolvers.py", line 619, in is_valid_path
    resolve(path, urlconf)
  File "/home/usgs/miniconda/envs/sci-wms/lib/python2.7/site-packages/django/core/urlresolvers.py", line 494, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/usgs/miniconda/envs/sci-wms/lib/python2.7/site-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/home/usgs/miniconda/envs/sci-wms/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/usgs/miniconda/envs/sci-wms/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/usgs/miniconda/envs/sci-wms/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/usgs/python/sci-wms/sciwms/urls.py", line 38, in <module>
    url(r'^rest/', include('wmsrest.urls')),
  File "/home/usgs/miniconda/envs/sci-wms/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/usgs/miniconda/envs/sci-wms/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/usgs/python/sci-wms/wmsrest/urls.py", line 4, in <module>
    from wmsrest.views import DatasetList, DatasetDetail, LayerDetail, VirtuallLayerDetail, DefaultDetail, DefaultList
  File "/home/usgs/python/sci-wms/wmsrest/views.py", line 5, in <module>
    from wmsrest.serializers import DatasetSerializer, SGridDatasetSerializer, UGridDatasetSerializer, RGridDatasetSerializer, LayerSerializer, VirtualLayerSerializer, VariableSerializer
  File "/home/usgs/python/sci-wms/wmsrest/serializers.py", line 29, in <module>
    class LayerSerializer(serializers.ModelSerializer):
  File "/home/usgs/python/sci-wms/wmsrest/serializers.py", line 31, in LayerSerializer
    default_style = DefaultStyleField(many=False)
  File "/home/usgs/miniconda/envs/sci-wms/lib/python2.7/site-packages/rest_framework/relations.py", line 38, in __init__
    'Relational field must provide a `queryset` argument, '
AssertionError: Relational field must provide a `queryset` argument, or set read_only=`True`.
```

**Comment by kwilcox** [comment]
The latest error you are seeing is from not running `migrate` after merging 0031 and 0034 into 0035. That's a good thing, because you shouldn't need to create 0035... doing so will put your database out of sync and prevent future updates.

The easiest solution would be to wait until a sci-wms commit is tagged as a release and use that. `master` has all tests passing but obviously has a bug when migrating from 0031 to 0034 cleanly in python 2.7. I'll take a look.

**Comment by kwilcox** [comment]
OK, we figured this out offline. The 0031 migration that Rich had was actually something that he created in the past (maybe another merge conflict due to different versions of libraries). He is going to start from scratch (and not make any migration files going forward!)

**Comment by rsignell-usgs** [comment]
Here's what I ended up doing:  wiping out everything and starting over.

How I removed my existing sci-wms installation and sci-wms python environment and using conda to reinstall is here:

https://github.com/USGS-CMG/usgs-cmg-portal/wiki/installing-sci-wms-with-anaconda

**Comment by ocefpaf** [comment]
@rsignell-usgs we can simplify those instructions a little bit.

These 4 steps:

```
conda install anaconda-client
conda install --file requirements.txt
conda install --file requirements-prod.txt
conda install --file requirements-test.txt
```

can be replaced by `conda install sci-wms`.  Our conda package **is** a metapackage that installs the dependencies listed in all those requirements files. 

The step:

```
# downgrade libspatialindex from 1.8.5 to 1.8.0
conda install --channel rustychris libspatialindex==1.8.0
```

Is problematic...  @kwilcox and I had a gchat about it and, to be honest, I lost faith in rtree.  The only configuration in which all tests passes are with debian's old `libspatialindex 1.7.0`.

I added the rtree tests to our conda package (see https://github.com/ioos/conda-recipes/pull/544/files).  The pickle test failures (`test_index`, `test_property`) are "OK".  The seg-fault seems to be unrelated to rtree and libspatialindex.  Besides, they do return the right answer when they I run outside conda-build.

However, the `test_stream_input` it not passing in any configuration.  The failure depend on the `libspatialindex` version. ( BTW I got our package to fail the same way as `rustychris libspatialindex==1.8.0`, so I don't see the reason for the downgrade above.)

I am not sure how sci-wms uses rtree internally to know if that is a problem for sci-wms, but the only way to get the tests passing is to avoid creating trees via the stream input.  Which is not an option!  Since the alternative is much slower :unamused: 

@kwilcox did you raise an issue at rtree repo?  If not I can do that tomorrow.

**Comment by ocefpaf** [comment]
BTW, just for the sake of reproducible results, [rustychris' libspatialindex](http://anaconda.org/rustychris/libspatialindex/files) is not 1.8.0 but 1.8.1.

You can check that with

``` python
from rtree import index
print(index.__c_api_version__)
```

Or just see his recipe below:

```
package:
  name: libspatialindex       # lower case name of package, may contain '-' but no spaces
  version: "1.8.0"    # source version
build:
  number: 2
source:
   # git then requires autoconf - easier to grab tarball
   #git_url: https://github.com/libspatialindex/libspatialindex.git
   fn: spatialindex-src-1.8.1.tar.gz
   url: http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.1.tar.gz
about:
  home: https://github.com/libspatialindex/libspatialindex
  license: MIT
  summary: C++ implementation of several spatial index algorithms
```

**Comment by rsignell-usgs** [comment]
Jeez, @ocefpaf, thanks for the detailed comments.  I've modified my instructions here
https://github.com/USGS-CMG/usgs-cmg-portal/wiki/installing-sci-wms-with-anaconda

And thanks for raising the rtree issue: https://github.com/Toblerity/rtree/issues/59
